package v1alpha1

import (
	"k8s.io/apimachinery/pkg/runtime"
	apiextensionsv1 "k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HyperConfig) DeepCopyInto(out *HyperConfig) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
}

func (in *HyperConfig) DeepCopy() *HyperConfig {
	if in == nil {
		return nil
	}
	out := new(HyperConfig)
	in.DeepCopyInto(out)
	return out
}

func (in *HyperConfig) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *HyperConfigList) DeepCopyInto(out *HyperConfigList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]HyperConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

func (in *HyperConfigList) DeepCopy() *HyperConfigList {
	if in == nil {
		return nil
	}
	out := new(HyperConfigList)
	in.DeepCopyInto(out)
	return out
}

func (in *HyperConfigList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// HyperRedis
func (in *HyperRedis) DeepCopyInto(out *HyperRedis) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
	in.Status.LastCheck.DeepCopyInto(&out.Status.LastCheck)
}

func (in *HyperRedis) DeepCopy() *HyperRedis {
	if in == nil {
		return nil
	}
	out := new(HyperRedis)
	in.DeepCopyInto(out)
	return out
}

func (in *HyperRedis) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *HyperRedisList) DeepCopyInto(out *HyperRedisList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]HyperRedis, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

func (in *HyperRedisList) DeepCopy() *HyperRedisList {
	if in == nil {
		return nil
	}
	out := new(HyperRedisList)
	in.DeepCopyInto(out)
	return out
}

func (in *HyperRedisList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// HyperPolicy
func (in *HyperPolicy) DeepCopyInto(out *HyperPolicy) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

func (in *HyperPolicySpec) DeepCopyInto(out *HyperPolicySpec) {
	*out = *in
	if in.Filters != nil {
		in, out := &in.Filters, &out.Filters
		*out = make([]FilterConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

func (in *FilterConfig) DeepCopyInto(out *FilterConfig) {
	*out = *in
	if in.Options != nil {
		in, out := &in.Options, &out.Options
		*out = new(apiextensionsv1.JSON)
		(*in).DeepCopyInto(*out)
	}
}

func (in *HyperPolicy) DeepCopy() *HyperPolicy {
	if in == nil {
		return nil
	}
	out := new(HyperPolicy)
	in.DeepCopyInto(out)
	return out
}

func (in *HyperPolicy) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *HyperPolicyList) DeepCopyInto(out *HyperPolicyList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]HyperPolicy, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

func (in *HyperPolicyList) DeepCopy() *HyperPolicyList {
	if in == nil {
		return nil
	}
	out := new(HyperPolicyList)
	in.DeepCopyInto(out)
	return out
}

func (in *HyperPolicyList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// HyperRoute
func (in *HyperRoute) DeepCopyInto(out *HyperRoute) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

func (in *HyperRouteSpec) DeepCopyInto(out *HyperRouteSpec) {
	*out = *in
	if in.Matches != nil {
		in, out := &in.Matches, &out.Matches
		*out = make([]MatchRule, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

func (in *MatchRule) DeepCopyInto(out *MatchRule) {
	*out = *in
	if in.Headers != nil {
		in, out := &in.Headers, &out.Headers
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

func (in *HyperRoute) DeepCopy() *HyperRoute {
	if in == nil {
		return nil
	}
	out := new(HyperRoute)
	in.DeepCopyInto(out)
	return out
}

func (in *HyperRoute) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *HyperRouteList) DeepCopyInto(out *HyperRouteList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]HyperRoute, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

func (in *HyperRouteList) DeepCopy() *HyperRouteList {
	if in == nil {
		return nil
	}
	out := new(HyperRouteList)
	in.DeepCopyInto(out)
	return out
}

func (in *HyperRouteList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}
