apiVersion: v1
kind: Service
metadata:
  name: hyper-operator
  namespace: hyper-system
spec:
  ports:
    - port: 443
      targetPort: 9443
      name: webhook
  selector:
    control-plane: controller-manager
