apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: hyper-validating-webhook-configuration
  annotations:
    cert-manager.io/inject-ca-from: hyper-system/hyper-operator-cert
webhooks:
  - name: vhyperchain.kb.io
    clientConfig:
      service:
        name: hyper-operator
        namespace: hyper-system
        path: /validate-hyper-io-v1alpha1-hyperchain
    failurePolicy: Fail
    rules:
      - apiGroups: ["hyper.io"]
        apiVersions: ["v1alpha1"]
        operations: ["CREATE", "UPDATE"]
        resources: ["hyperchains"]
    admissionReviewVersions: ["v1"]
    sideEffects: None

  - name: vfilters.kb.io
    clientConfig:
      service:
        name: hyper-operator
        namespace: hyper-system
        path: /validate-hyper-io-v1alpha1-filter
    failurePolicy: Fail
    rules:
      - apiGroups: ["hyper.io"]
        apiVersions: ["v1alpha1"]
        operations: ["DELETE"]
        resources: 
          - "oidcfilters"
          - "ratelimitfilters"
          - "headermodifierfilters"
          - "denyfilters"
          - "correlationidfilters"
          - "redismetadataenricherfilters"
    admissionReviewVersions: ["v1"]
    sideEffects: None
