FROM ubuntu:24.04

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install -y --no-install-recommends \
    sudo curl wget git ca-certificates jq iproute2 tcpdump dnsutils net-tools \
    bash-completion tar gzip build-essential \
    python3 python3-pip python3-venv python3-dev \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

RUN ARCH=$(uname -m | sed -e 's/x86_64/amd64/' -e 's/aarch64/arm64/') \
    && curl -L "https://github.com/mikefarah/yq/releases/latest/download/yq_linux_${ARCH}" -o /usr/local/bin/yq \
    && chmod +x /usr/local/bin/yq \
    && curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 \
    && bash get_helm.sh && rm get_helm.sh \
    && curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/${ARCH}/kubectl" \
    && install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl && rm kubectl \
    && curl -Lo ./kind https://kind.sigs.k8s.io/dl/latest/kind-linux-${ARCH} \
    && chmod +x ./kind && mv ./kind /usr/local/bin/kind

RUN GOOS=$(uname -s | tr '[:upper:]' '[:lower:]') \
    && GOARCH=$(uname -m | sed -e 's/x86_64/amd64/' -e 's/aarch64/arm64/') \
    && CILIUM_CLI_VERSION=$(curl -s https://raw.githubusercontent.com/cilium/cilium-cli/main/stable.txt) \
    && curl -L --fail https://github.com/cilium/cilium-cli/releases/download/${CILIUM_CLI_VERSION}/cilium-${GOOS}-${GOARCH}.tar.gz | tar -xzf - -C /usr/local/bin \
    && HUBBLE_VERSION=$(curl -s https://raw.githubusercontent.com/cilium/hubble/master/stable.txt) \
    && curl -L --fail https://github.com/cilium/hubble/releases/download/${HUBBLE_VERSION}/hubble-${GOOS}-${GOARCH}.tar.gz | tar -xzf - -C /usr/local/bin


RUN curl -1sLf 'https://dl.cloudsmith.io/public/task/task/setup.deb.sh' | sudo -E bash && apt update && apt upgrade -y
RUN apt install task 
RUN rm -rf /usr/local/go && curl -fsSL https://go.dev/dl/go1.26.4.linux-amd64.tar.gz | tar -C /usr/local -xzf -

RUN curl -L https://github.com/cilium/tetragon/releases/latest/download/tetra-linux-amd64.tar.gz | tar -xz
RUN mv tetra /usr/local/bin